version: '3.8'
services:
   web:
       build: .
       command: bash -c "python src/preprocess.py && python src/train.py && python src/predict.py -m RAND_FOREST -t func && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m"
       ports:
           - 8000:8000
       image: synphase/big_data_lab_2:latest
   postgres:
       image: postgres:latest
       container_name: postgres
       environment:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
           POSTGRES_DB: database
       ports:
          - "5432:5432"
       volumes:
          - pgdata:/var/lib/postgresql/data

volumes:
   pgdata: