pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('big_data_lab_3')
        VAULT_CREDS=credentials('ansible_vault')
        LC_ALL   = "en_US.UTF-8"
        LANG     = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
        stage('Clone github repository') {
            steps {
                cleanWs()
                sh 'git clone -b main https://github.com/NikitaSelin/big_data_lab_3.git'
			}
		}

        stage('Checkout repo dir') {
            steps {
                sh 'cd big_data_lab_3 && dir'
			}
	    }

        stage('Login') {
            steps {
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Create password file') {
            steps {
                sh 'cd big_data_lab_3 && touch ansible-password.txt && echo $VAULT_CREDS_PSW >> ansible-password.txt'
            }
        }

        stage('Create environment') {
            steps {
                sh 'cd big_data_lab_3 && ansible-playbook setup.yml --vault-password-file ansible-password.txt'
            }
        }

        stage('Building docker') {
            steps {
                sh 'cd big_data_lab_3 && docker compose build'
            }
        }
        stage('Create and run docker container') {
            steps {
                sh 'cd big_data_lab_3 && docker compose up -d'
            }
        }

        stage('Checkout coverage report') {
            steps{
                dir("big_data_lab_3") {
                    sh 'docker compose logs -t --tail 10'
                }
            }
        }

        stage('Push') {
            steps {
                sh 'docker push synphase/big_data_lab_3:latest'
            }
        }
	}

    post {
        always {
            sh 'docker logout'
        }
    }
}